@startuml
' Two actors as players, giving an alias for simplier writing later
actor p1 as "Player 1"
actor p2 as "Player 2"

' The grid the game is played on
participant grid as "Game Grid"

' The core loop of the game
loop While Game is Not Over
    alt Player One's Turn
        p1 -> grid : Choose an open position
        p1 -> p2 : Change to Player Two's Turn        
    else Player Two's Turn
        p2 -> grid : Choose an open position
        p2 -> p1 : Change to Player One's Turn        
    end
end
@enduml